sonar.projectKey=mindbridge
sonar.projectName=MindBridge
sonar.sources=.
sonar.exclusions=.venv/**,tests/**,client_data/**,saved_model/**,data/**,**/*.png,**/__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
